src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AccountRepository::class)
 */
class Account
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $balance;

    /**
     * @ORM\OneToMany(targetEntity=Transfer::class, mappedBy="account", cascade={"persist", "remove"})
     */
    private $transfers;

    /**
     * @ORM\ManyToOne(targetEntity=Banker::class, inversedBy="accounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $banker;

    /**
     * @ORM\OneToOne(targetEntity=Customer::class, mappedBy="account", cascade={"persist", "remove"})
     */
    private $customer;

    /**
     * @ORM\Column(type="string", length=11, nullable=true)
     */
    private $bank_account_id;

    /**
     * @ORM\Column(type="boolean", options={ "default" : false } )
     */
    private $toDeleted;

    public function __construct()
    {
        $this->transfers = new ArrayCollection();
        $this->balance = 0.0;
        $this->toDeleted = false;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBalance(): ?float
    {
        return $this->balance;
    }

    public function setBalance(float $balance): self
    {
        $this->balance = $balance;

        return $this;
    }

    /**
     * @return Collection|Transfer[]
     */
    public function getTransfers(): Collection
    {
        return $this->transfers;
    }

    public function addTransfer(Transfer $transfer): self
    {
        if (!$this->transfers->contains($transfer)) {
            $this->transfers[] = $transfer;
            $transfer->setAccount($this);
        }

        return $this;
    }

    public function removeTransfer(Transfer $transfer): self
    {
        if ($this->transfers->removeElement($transfer)) {
            // set the owning side to null (unless already changed)
            if ($transfer->getAccount() === $this) {
                $transfer->setAccount(null);
            }
        }

        return $this;
    }

    public function getBanker(): ?Banker
    {
        return $this->banker;
    }

    public function setBanker(?Banker $banker): self
    {
        $this->banker = $banker;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        // unset the owning side of the relation if necessary
        if ($customer === null && $this->customer !== null) {
            $this->customer->setAccount(null);
        }

        // set the owning side of the relation if necessary
        if ($customer !== null && $customer->getAccount() !== $this) {
            $customer->setAccount($this);
        }

        $this->customer = $customer;

        return $this;
    }

    public function getBankAccountId(): ?string
    {
        return $this->bank_account_id;
    }

    public function setBankAccountId(): self
    {
        // if id is set or bank_account_id already generate do nothing
        if ( $this->id && ! $this->bank_account_id) {
            $begin = substr( date("ymd", time() ) , -5 );
            $end = substr("0000" . $this->id, -5 );
            $key = (int) ($begin . $end ) % 8;
            $this->bank_account_id = $begin . $end . $key;
        }

        return $this;
    }

    public function getToDeleted(): ?bool
    {
        return $this->toDeleted;
    }

    public function setToDeleted(bool $toDeleted): self
    {
        $this->toDeleted = $toDeleted;

        return $this;
    }
}

src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_path;

    /**
     * @ORM\OneToOne(targetEntity=Account::class, inversedBy="customer", cascade={"persist", "remove"})
     */
    private $account;

    /**
     * @ORM\OneToMany(targetEntity=Beneficiary::class, mappedBy="customer", cascade={"persist", "remove"})
     */
    private $Beneficiaries;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="customer", cascade={"persist", "remove"})
     */
    private $user;

    public function __construct()
    {
        $this->Beneficiaries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getIdPath(): ?string
    {
        return $this->id_path;
    }

    public function setIdPath(string $id_path): self
    {
        $this->id_path = $id_path;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }

    /**
     * @return Collection|Beneficiary[]
     */
    public function getBeneficiaries(): Collection
    {
        return $this->Beneficiaries;
    }

    public function addBeneficiary(Beneficiary $beneficiary): self
    {
        if (!$this->Beneficiaries->contains($beneficiary)) {
            $this->Beneficiaries[] = $beneficiary;
            $beneficiary->setCustomer($this);
        }

        return $this;
    }

    public function removeBeneficiary(Beneficiary $beneficiary): self
    {
        if ($this->Beneficiaries->removeElement($beneficiary)) {
            // set the owning side to null (unless already changed)
            if ($beneficiary->getCustomer() === $this) {
                $beneficiary->setCustomer(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setCustomer(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getCustomer() !== $this) {
            $user->setCustomer($this);
        }

        $this->user = $user;

        return $this;
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\Account;
use App\Entity\Customer;
use App\Entity\User;
use App\Form\AddCustomerType;
use App\Repository\AccountRepository;
use App\Repository\BankerRepository;
use App\Repository\CustomerRepository;
use App\Repository\UserRepository;
use App\Services\myServices;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class CustomerController extends AbstractController
{
    /**
     * @Route("/add-customer", name="customer")
     */
    public function addCustomer(
        Request $request,
        UserRepository $userRepository,
        BankerRepository $bankerRepository,
        UserPasswordEncoderInterface $passwordEncoder,
        myServices $services
    ): Response
    {

        $form = $this->createForm(AddCustomerType::class);

        $form->handleRequest($request);

        if ( $form->isSubmitted() && $form->isValid() ) {
            $data = $form->getData();
            $thereAreErrors = false;
            // we check if the email is already in database
            if ( $userRepository->findOneBy(['email' => $data['email'], ]) ) {
                $form['email']->addError( new FormError('Cette adresse mail est dèjà utilisée'));
                $thereAreErrors = true;
            }
            // check password complexity
            if (! $services->passwordIsComplex($data['password'])) {
                $form['password']->addError( new FormError('Le mot de passe répondre au exigences de complexité'));
                $thereAreErrors = true;
            }
            // check file type ( image or pdf )
            if ( ! $this->fileVerification($data['file'])) {
                $form['file']->addError( new FormError('Ce type de fichier n\'est pas autorisé'));
                $thereAreErrors = true;
            }
            // no errors detected continue process
            if ( ! $thereAreErrors ) {
                // create the new user (user, Customer & Account class )
                $user = new User();
                $customer = new Customer();
                $account = new Account();

                $user->setEmail($data['email']);
                $user->setPassword($passwordEncoder->encodePassword($user, $data['password'] ));
                $user->setRoles(['ROLE_CUSTOMER']);
                $user->setLastname($data['lastname']);
                $user->setFirstname($data['firstname']);
                $user->setCustomer($customer);

                $customer->setBirthday($data['birthday']);
                $customer->setAdress($data['adress']);
                $customer->setZipCode($data['zipCode']);
                $customer->setCity($data['city']);
                // give a name to the file and move it in the directory define inparameter
                $fichier= md5(uniqid()) . time() . '.' . $data['file']->guessExtension();
                $customer->setIdPath($fichier);
                $data['file']->move(
                    $this->getParameter('id_images_directory'),
                    $fichier
                );
                $customer->setUser($user);
                $customer->setAccount($account);

                $account->setCustomer($customer);
                $account->setBanker($bankerRepository->findBankerWithLeastAccount());

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($user);
                $entityManager->flush();
                // all is good and inform user
                return $this->render('displayInfo.html.twig', [
                    'title' => 'Demande de création de compte effectuer.',
                    'contentTitle' => 'Votre demande a été prise en compte',
                    'content' => [ 'Votre demande a bien été prise en compte.',
                        'Après vérification votre compte sera validé par l\'un de nos collaborateurs',
                        'Merci pour votre confiance et a bientôt',
                    ],
                ]);
            }
        }

        return $this->render('customer/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/customer-delete", name="customer_delete")
     * @IsGranted("ROLE_VALIDATED_CUSTOMER")
     */
    public function delCustomer(
        Request $request,
        CustomerRepository $customerRepository
    ): Response
    {
        if(empty($this->getUser())) {
            return $this->render('displayInfo.html.twig', [
                'title' => 'Demande de suppresion de compte effectuer.',
                'contentTitle' => 'Votre demande a été prise en compte',
                'content' => [ 'Votre demande a bien été prise en compte.',
                    'Après vérification votre compte sera supprimé par l\'un de nos collaborateurs',
                    'Merci pour votre confiance et a bientôt',
                ],
            ]);

        }

        // create form
        $form = $this->createFormBuilder()
            ->add(
                'checkConfirmation',
                CheckboxType::class,
                [
                    'label' => 'Veuillez confirmer votre demande de suppression de compte en cochant cette case',
                        'attr' => [
                        // Add JS for enabled en disable confirm button
                        'onchange' => 'document.getElementById(\'confirmButton\').disabled = !this.checked;'
                    ]
                ])
            ->getForm();

        $form->handleRequest($request);

        if ( $form->isSubmitted() && $form->isValid() ) {
            $data = $form->getData();
            if($data['checkConfirmation']) {

                $user = $this->getUser();
                $user->setRoles(['ROLE_TO_DELETED_CUSTOMER']);

                $user->getCustomer()->getAccount()->setToDeleted(true);

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($user);
                $entityManager->flush();

                return $this->redirectToRoute('customer_delete');
            }
        }

        return $this->render('customer/customer_delete.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/customer-delete-validation", name="customer_delete_validation")
     * @IsGranted("ROLE_BANKER")
     */
    public function customerDeleteValidation() : Response
    {
        return $this->redirectToRoute('customer_delete_validation_page', [ 'page' => 1 ]);
    }

    /**
     * @Route("/customer-delete-validation/{page}", name="customer_delete_validation_page")
     * @IsGranted("ROLE_BANKER")
     */
    public function customerDeleteValidationPage(
        int $page,
        AccountRepository $accountRepository,
        Request $request
    ) : Response
    {
        $banker = $this->getUser()->getBanker();

        $paginationLimite =  $this->getParameter('paginationLimite');
        $nbRow = $accountRepository->numberOfAccountToDelete($banker);

        // case where there is still no transfer made
        $lastPage = $nbRow == 0 ? 1 : ceil( $nbRow / $paginationLimite);
        // if the page is out of bounds redirect to first hors last page
        if ( $page > $lastPage) {
            return $this->redirectToRoute($request->attributes->get('_route'), [ 'page' => $lastPage ]);
        }
        if ( $page < 1 ) {
            return $this->redirectToRoute($request->attributes->get('_route'), [ 'page' => 1 ]);
        }

        $accounts = $accountRepository->findBy([
            'banker' => $banker,
            'toDeleted' => true ],
            [],
            $paginationLimite,
            $paginationLimite * ( $page - 1 )
        );
        return $this->render('customer/customer_delete_validation.html.twig', [
            'accounts' => $accounts,
            'routeName' => $request->attributes->get('_route'),
            'currentPage' => $page,
            'lastPage' => $lastPage,
        ]);
    }



    /**
     * @Route("/customer-delete/{id}")
     * @IsGranted("ROLE_BANKER")
     */
    public function customerDelete(
        int $id,
        AccountRepository $accountRepository,
        EntityManagerInterface $entityManager
    ) : Response
    {

        $account = $accountRepository->findOneBy([
           'bank_account_id' => $id,
            'toDeleted' => true,
        ]);
        if ( empty($account) ) {
            return $this->render('displayInfo.html.twig', [
                'title' => 'Erreur de suppression.',
                'contentTitle' => 'Erreur lors de la suppression du compte',
                'content' => [ 'Erreur lors de la suppression du compte.',
                    'Veuillez vérifier la demande de suppresion et réessayé la confirmation de suppresion',
                ],
            ]);

        }

        $entityManager->remove($account->getCustomer()->getUser());
        $entityManager->flush();

        return $this->render('displayInfo.html.twig', [
            'title' => 'Suppresion de compte effectuer.',
            'contentTitle' => 'Le compte a été supprimé',
            'content' => [ 'Le compte N° ' . $account->getBankAccountId() . ' a bien supprimé.',
            ],
        ]);
    }

    /**
     * function checks if the file type is allowed
     *
     * @param UploadedFile $file file to verify
     *
     * @return boolean
     */
    private function fileVerification(UploadedFile $file) : bool {

templates/customer/customer_delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Suppresion de compte{% endblock %}

{% block page_title %}Suppresion de votre compte.{% endblock %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-row mt-3">
        <h4 class="font-weight-bold text-danger text-justify">Si vous demandez la suppression de votre compte, celui-ci ne sera plus disponible une fois confirmer et supprimer par l'un de nos collaborateurs</h4>
    </div>
    <div class="form-row mt-3">
        {{ form_label( form.checkConfirmation ) }}
        {{ form_widget( form.checkConfirmation ) }}
    </div>
    <div class="form-row mt-3 justify-content-center">
        <button type="button" class="btn btn-outline-primary col-6" data-toggle="modal" data-target="#confirmeModal" disabled="true" id="confirmButton">
            Demander la suppression de votre compte
        </button>

        <!-- Modal -->
        <div class="modal fade" id="confirmeModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmModalLabel">Suppresion de compte</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Etes vous sur de vouloir supprimer votre compte ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <input type="submit" class="btn btn-outline-primary col-6" value="Confirmer la demande" >
                    </div>
                </div>
            </div>
        </div>
        <div class="container  text-center">
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/customer/customer_delete_validation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supresion de comptes{% endblock %}

{% block page_title %}Comptes à supprimer.{% endblock %}
{% block body %}
    {% if accounts is empty %}
       Il n'y aucun compte a valider.
    {% else %}
        <div class="row">
            {# List group #}
            <div class="col-lg-4 col-12 p-0 order-1 order-lg-0 list-group border" id="list-tab" role="tablist">
                {% for account in accounts %}
                    <a class="list-group-item list-group-item-action{% if loop.index == 1 %} active{% endif %}"
                       id="list-{{ account.customer.id }}-list"
                       data-toggle="list"
                       href="#list-{{ account.customer.id }}"
                       role="tab"
                       aria-controls="customer{{ account.customer.id }}">
                        {{ account.customer.user.lastname}} {{ account.customer.user.firstname}}
                    </a>
                {% endfor %}
            </div>
            {# Tab panes #}
            <div class="tab-content col-lg-8 col-12 order-0 order-lg-1" id="nav-tabContent">
                {% for account in accounts %}
                    {% set uniqId = account.customer.idPath|split('.').0 %}
                    <div class="tab-pane fade border rounded-lg p-2{% if loop.index == 1 %} show active{% endif %}"
                         id="list-{{ account.customer.id }}"
                         role="tabpanel"
                         aria-labelledby="list-{{ account.customer.id }}-list">
                        <p class="font-weight-bold">COMPTE N°{{ account.bankAccountId }}<br />{{ account.customer.user.lastname}} {{ account.customer.user.firstname}}</p>
                        <p class="font-weight-bold"></p>
                        <p class="pl-3">{{ account.customer.user.email}}</p>
                        <p class="pl-3 text-justify">{{ account.customer.adress }} <br />{{ account.customer.zipCode }} <span class="text-uppercase">{{ account.customer.city }}</span></p>
                        <button type="button" class="btn btn-outline-primary btn-block" data-toggle="modal" data-target="#modal{{ account.bankAccountId }}">Supprimer le compte</button>
                    </div>
                {% endfor %}
            </div>
        </div>
        {#  #}
        {% for account in accounts %}
            {% set uniqId = account.customer.idPath|split('.').0 %}
            <div class="modal fade" id="modal{{ account.bankAccountId }}" tabindex="-1" role="dialog" aria-labelledby="modal{{ account.bankAccountId }}Title" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modal{{ account.bankAccountId }}LongTitle">{{ account.bankAccountId}}-{{ account.customer.user.lastname}} {{ account.customer.user.firstname}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Êtes-vous sur de vouloir supprimer ce compte</label>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                            <a type="button" class="btn btn-primary" href="/customer-delete/{{ account.bankAccountId }}" aria-disabled="true">Confirmer</a>
                        </div>
                    </div>
                </div>
            </div>
        {%  endfor %}
        {% if lastPage > 1 %}
            {% include '_paging.html.twig' %}
        {% endif %}
    {% endif %}
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demande de création de compte{% endblock %}

{% block page_title %}Demande de création de compte{% endblock %}
{% block body %}
    {{ form_start(form) }}
    {{ form_errors(form) }}
    <div class="form-row">
        <div class="form-group col-12">
            {{ form_label(form.email) }}
            {{ form_widget(form.email) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-6">
            {{ form_label(form.password.first) }}
            {{ form_errors(form.password) }}
            {{ form_widget(form.password.first) }}
            {{ form_help(form.password) }}
        </div>
        <div class="form-group col-lg-6">
            {{ form_label(form.password.second) }}
            {% if form_errors(form.password) %}<br /><br />{% endif %}
            {{ form_widget(form.password.second) }}
        </div>
    </div>
    <div class="form-row mt-2">
        <div class="form-group col-lg-6">
            {{ form_label(form.lastname) }}
            {{ form_widget(form.lastname) }}
        </div>
        <div class="form-group col-lg-6">
            {{ form_label(form.firstname) }}
            {{ form_widget(form.firstname) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-3">
            {{ form_label(form.birthday) }}
            {{ form_widget(form.birthday) }}
        </div>
    </div>
{{ form_row(form.adress) }}

<div class="form-row">
    <div class="form-group col-lg-4">
        {{ form_label(form.zipCode) }}
        {{ form_widget(form.zipCode) }}
    </div>
    <div class="form-group col-lg-8">
        {{ form_label(form.city) }}
        {{ form_widget(form.city) }}
    </div>

</div>
<div class="form-row">
        {{ form_row(form.file) }}
</div>
<div class="form-row">
    <div class="container text-center">
        <input type="submit" class="btn btn-outline-primary col-6" value="Valider" >
    </div>
</div>
{{ form_end(form) }}
{% endblock %}