src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_path;

    /**
     * @ORM\OneToOne(targetEntity=Account::class, inversedBy="customer", cascade={"persist", "remove"})
     */
    private $account;

    /**
     * @ORM\OneToMany(targetEntity=Beneficiary::class, mappedBy="customer", cascade={"persist", "remove"})
     */
    private $Beneficiaries;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="customer", cascade={"persist", "remove"})
     */
    private $user;

    public function __construct()
    {
        $this->Beneficiaries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getIdPath(): ?string
    {
        return $this->id_path;
    }

    public function setIdPath(string $id_path): self
    {
        $this->id_path = $id_path;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }

    /**
     * @return Collection|Beneficiary[]
     */
    public function getBeneficiaries(): Collection
    {
        return $this->Beneficiaries;
    }

    public function addBeneficiary(Beneficiary $beneficiary): self
    {
        if (!$this->Beneficiaries->contains($beneficiary)) {
            $this->Beneficiaries[] = $beneficiary;
            $beneficiary->setCustomer($this);
        }

        return $this;
    }

    public function removeBeneficiary(Beneficiary $beneficiary): self
    {
        if ($this->Beneficiaries->removeElement($beneficiary)) {
            // set the owning side to null (unless already changed)
            if ($beneficiary->getCustomer() === $this) {
                $beneficiary->setCustomer(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setCustomer(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getCustomer() !== $this) {
            $user->setCustomer($this);
        }

        $this->user = $user;

        return $this;
    }
}

src/Controller/ValideCustomerController.php
<?php

namespace App\Controller;

use App\Repository\AccountRepository;
use App\Repository\CustomerRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ValideCustomerController extends AbstractController
{
    /**
     * @Route("/valide-customers", name="valide_customers")
     * @IsGranted("ROLE_BANKER")
     */
    public function index(): Response
    {
        return $this->redirectToRoute('valide_customers_page', [ 'page' => 1 ]);
    }

    /**
     * @Route("/valide-customers/{page}", name="valide_customers_page")
     * @IsGranted("ROLE_BANKER")
     */
    public function valideCustomerPage(
        int $page,
        AccountRepository $accountRepository,
        Request $request
    ): Response
    {

        $banker = $this->getUser()->getBanker();
        $paginationLimite =  $this->getParameter('paginationLimite');
        $nbRow = $accountRepository->numberOfAccountTovalidate($banker);

        // case where there is still no transfer made
        $lastPage =  $nbRow == 0 ? 1 : ceil( $nbRow / $paginationLimite );

        // if the page is out of bounds redirect to first hors last page
        if ( $page > $lastPage) {
            return $this->redirectToRoute($request->attributes->get('_route'), [ 'page' => $lastPage ]);
        }
        if ( $page < 1 ) {
            return $this->redirectToRoute($request->attributes->get('_route'), [ 'page' => 1 ]);
        }

        $accounts = $accountRepository->findBy([
            'bank_account_id' => null,
            'banker' => $banker->getId() ],
            [],
            $paginationLimite,
            $paginationLimite * ( $page - 1 )
        );

        return $this->render('valide_customer/index.html.twig', [
            'accounts' => $accounts,
            'routeName' => $request->attributes->get('_route'),
            'currentPage' => $page,
            'lastPage' => $lastPage,
        ]);
    }


    /**
     * @Route("/valide-customer-id/{id}", name="download_id" )
     * @IsGranted("ROLE_BANKER")
     */
    public function downloadIdImage(
        string $id,
        CustomerRepository $customerRepository
    ) : Response
    {

        $path = $this->getParameter('id_images_directory');
        $filename = $customerRepository->findByIdPath($id)->getIdPath();

        $content = file_get_contents($path.'/'.$filename);

        $response = new Response();

        //set headers
        $response->headers->set('Content-Type', 'mime/type');
        $response->headers->set('Content-Disposition', 'attachment;filename="'.$filename);

        $response->setContent($content);

        return $response;
    }

    /**
     * @Route("/valide-customer/{id}")
     * @IsGranted("ROLE_BANKER")
     */
    public function valideAccountCustomer(
        string $id,
        CustomerRepository $customerRepository
    ) : Response
    {
        // Set the bank account id
        $account = $customerRepository->findByIdPath($id)->getAccount();
        $account->setBankAccountId();
        $account->getCustomer()->getUser()->setRoles(["ROLE_VALIDATED_CUSTOMER"]);
        // Add update in database.
        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->persist($account);
        $entityManager->flush();
        // return to valide customer module
        return $this->redirectToRoute('valide_customers');
    }
}

templates/valide_customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Validation des comptes{% endblock %}

{% block page_title %}Liste des comptes à valider{% endblock %}

{% block body %}
    {% if accounts is empty %}
        Il n'y aucun compte a valider.
    {% else %}
    <div class="row">
        {# List group #}
        <div class="col-lg-4 col-12 p-0 order-1 order-lg-0 list-group border" id="list-tab" role="tablist">
            {% for account in accounts %}
            <a class="list-group-item list-group-item-action{% if loop.index == 1 %} active{% endif %}"
                id="list-{{ account.customer.id }}-list"
                data-toggle="list"
                href="#list-{{ account.customer.id }}"
                role="tab"
                aria-controls="customer{{ account.customer.id }}">
                    {{ account.customer.user.lastname}} {{ account.customer.user.firstname}}
            </a>
            {% endfor %}
        </div>
        {# Tab panes #}
        <div class="tab-content col-lg-8 col-12 order-0 order-lg-1" id="nav-tabContent">
            {% for account in accounts %}
                {% set uniqId = account.customer.idPath|split('.').0 %}
                <div class="tab-pane fade border rounded-lg  mb-2 p-2{% if loop.index == 1 %} show active{% endif %}"
                     id="list-{{ account.customer.id }}"
                     role="tabpanel"
                     aria-labelledby="list-{{ account.customer.id }}-list">
                    <p class="font-weight-bold">{{ account.customer.user.lastname}} {{ account.customer.user.firstname}}</p>
                    <p class="pl-3">{{ account.customer.user.email}}</p>
                    <p class="pl-3 text-justify">{{ account.customer.adress }} <br />{{ account.customer.zipCode }} <span class="text-uppercase">{{ account.customer.city }}</span></p>
                    <a type="button" class="btn btn-outline-primary btn-block" href="/valide-customer-id/{{ uniqId }}" >Visualiser la piece d'identité</a>
                    <button type="button" class="btn btn-outline-primary btn-block" data-toggle="modal" data-target="#modal{{ uniqId }}">Valider le compte</button>
                </div>
            {% endfor %}
        </div>
    </div>
    {#  #}
    {% for account in accounts %}
        {% set uniqId = account.customer.idPath|split('.').0 %}
    <div class="modal fade" id="modal{{ uniqId }}" tabindex="-1" role="dialog" aria-labelledby="modal{{ uniqId }}Title" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal{{ uniqId }}LongTitle">{{ account.customer.user.lastname}} {{ account.customer.user.firstname}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Etes-vous sur de vouloir valider ce compte ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <a type="button" class="btn btn-primary" href="/valide-customer/{{ uniqId }}">Confirmer</a>
                </div>
            </div>
        </div>
    </div>
    {%  endfor %}
    {% if lastPage > 1 %}
        {% include '_paging.html.twig' %}
    {% endif %}
    {% endif %}
{% endblock %}